/**
 * Shared identifiers for the deterministic e2e stack.
 *
 * Every value here comes from `db/test-fixture.sql` (regenerated by
 * `prisma/seed-test-fixtures.ts`, documented in `db/README.md`). No real
 * participant data, credentials, or imagery appears in this directory.
 */

export const SESSION_ES = {
    id: '10000000-0000-4000-8000-000000000101',
    title: 'Sesión en Español (test)',
    roomName: 'weekend-test-spanish',
} as const;

export const SESSION_EN = {
    id: '10000000-0000-4000-8000-000000000102',
    title: 'English Session (test)',
    roomName: 'weekend-test-english',
} as const;

export const TICKETS = {
    /** ISSUED — binds to whatever email logs in first. */
    esIssuedA: 'TEST-TEST-TEST-TESA',
    /** BOUND — only valid together with its bound email. */
    esBound: { code: 'TEST-TEST-TEST-TESD', email: 'asistente@altermundi.net' },
    /** REVOKED — login must fail with the generic error. */
    esRevoked: 'TEST-TEST-TEST-TESE',
    /** ISSUED for capability guidance; isolated from lifecycle/contribution specs. */
    esIssuedC: 'TEST-TEST-TEST-TESC',
    /** ISSUED for capability guidance; isolated from lifecycle/contribution specs. */
    enIssuedC: 'TEST-TEST-TEST-TENC',
    /** ISSUED for the English fixture; reserved for the second lifecycle E2E. */
    enIssuedB: 'TEST-TEST-TEST-TENB',
} as const;

/** All fixture staff accounts share the documented password `test`. */
export const STAFF = {
    facilitator: { email: 'facilitator@altermundi.net', password: 'test' },
    operator: { email: 'operator1@altermundi.net', password: 'test' },
    admin: { email: 'admin@altermundi.net', password: 'test' },
} as const;

export const ROUTES = {
    landing: '/',
    staffLogin: '/staff/login',
    opsHealth: '/ops/health',
    opsAdmission: '/ops/admission',
    opsEvents: '/ops/events',
    session: (id: string) => `/session/${id}`,
    opsSession: (id: string) => `/ops/events/${id}`,
} as const;
