/**
 * Shared test fixtures — the seed behind db/test-fixture.sql.
 *
 * Creates a complete, deterministic testing dataset: four staff users (all
 * with the password "test"), the two 2026-08-08 weekend sessions, and ticket
 * entitlements in every relevant state (ISSUED, BOUND, REVOKED, COMP).
 *
 * This script is self-contained: it does NOT read the production seed
 * contract (STAFF_* / WEEKEND_* env vars), only DATABASE_URL and
 * TICKET_CODE_PEPPER. Ticket digests are computed with whatever pepper the
 * local environment provides, so any developer can re-run it against their
 * own database. The committed db/test-fixture.sql dump is generated with the
 * pinned test-only pepper documented in db/README.md — anyone restoring the
 * dump must use that same pepper.
 *
 * Idempotent: safe to re-run. Re-running also refreshes ticket expiry, which
 * matters once the event date has passed.
 *
 * Usage:
 *   npx tsx prisma/seed-test-fixtures.ts
 * or:
 *   npm run db:seed:test
 */

// dotenv loaded from env in dev; production sets vars directly
let configDotenv: ((opts: { path: string }) => void) | undefined;
try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const dotenv = require('dotenv');
    configDotenv = dotenv.config;
} catch {
    // dotenv not available; env vars are already set
}
if (configDotenv) {
    configDotenv({ path: '.env.local' });
    configDotenv({ path: '.env' });
}

import { scrypt } from 'node:crypto';
import { promisify } from 'node:util';

import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, StaffRole, TicketTier } from '@prisma/client';
import { Pool } from 'pg';

import { ticketExpiresAt } from '../src/lib/admission';
import { ticketCodeStorage } from '../src/lib/ticket-code';
import { transitionParticipantGrant } from '../src/lib/stage-grant-effects';
import {
    lockGrantParticipants,
    lockGrantSession,
    lockGrantStaff,
} from '../src/lib/stage-grant-locks';

const scryptAsync = promisify(scrypt);

export const TEST_STAFF_PASSWORD = 'test';

/**
 * Fixed per-user salts keep the digests reproducible, so the committed
 * db/test-fixture.sql can be regenerated byte-identically. These are
 * test-only accounts — the fixed salts are a feature (reproducibility), not
 * a security concern.
 */
const STAFF_FIXTURES: ReadonlyArray<{
    name: string;
    email: string;
    role: StaffRole;
    salt: string;
}> = [
    { name: 'Test Facilitator', email: 'facilitator@altermundi.net', role: 'FACILITATOR', salt: 'fixture-salt-fac01' },
    { name: 'Test Operator One', email: 'operator1@altermundi.net', role: 'OPERATOR', salt: 'fixture-salt-op001' },
    { name: 'Test Operator Two', email: 'operator2@altermundi.net', role: 'OPERATOR', salt: 'fixture-salt-op002' },
    { name: 'Test Admin', email: 'admin@altermundi.net', role: 'ADMIN', salt: 'fixture-salt-adm01' },
];

/** Both sessions on Saturday 2026-08-08; times are the database truth (CR = UTC-6). */
const SESSION_FIXTURES: ReadonlyArray<{
    id: string;
    title: string;
    description: string;
    roomName: string;
    language: 'ENGLISH' | 'SPANISH';
    scheduledAt: Date;
    tier: TicketTier;
    codePrefix: string;
}> = [
    {
        id: '10000000-0000-4000-8000-000000000101',
        title: 'Harmonic Projection — Sesión en Español (test)',
        description: 'Test fixture session. Spanish, Saturday 2026-08-08 08:30 Costa Rica.',
        roomName: 'weekend-test-spanish',
        language: 'SPANISH',
        scheduledAt: new Date('2026-08-08T14:30:00.000Z'), // 08:30 America/Costa_Rica
        tier: 'GLOBAL_SOUTH',
        codePrefix: 'TEST-ES',
    },
    {
        id: '10000000-0000-4000-8000-000000000102',
        title: 'Harmonic Projection — English Session (test)',
        description: 'Test fixture session. English, Saturday 2026-08-08 14:00 Costa Rica.',
        roomName: 'weekend-test-english',
        language: 'ENGLISH',
        scheduledAt: new Date('2026-08-08T20:00:00.000Z'), // 14:00 America/Costa_Rica
        tier: 'GLOBAL_NORTH',
        codePrefix: 'TEST-EN',
    },
];

const ATTENDEE_EMAILS: Record<string, string> = {
    'TEST-ES': 'asistente@altermundi.net',
    'TEST-EN': 'attendee@altermundi.net',
};

async function digestTestPassword(salt: string): Promise<string> {
    const saltBuffer = Buffer.from(salt, 'utf8');
    if (saltBuffer.length < 16) {
        throw new Error(`Fixture salt "${salt}" must be at least 16 bytes`);
    }
    const digest = (await scryptAsync(TEST_STAFF_PASSWORD, saltBuffer, 32)) as Buffer;
    return `scrypt$${saltBuffer.toString('base64url')}$${digest.toString('base64url')}`;
}

async function main() {
    const databaseUrl = process.env.DATABASE_URL?.trim();
    if (!databaseUrl) {
        throw new Error('Missing required environment variable: DATABASE_URL');
    }

    const pool = new Pool({ connectionString: databaseUrl });
    const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

    try {
        const summary = await prisma.$transaction(async (tx) => {
            // ── Staff ────────────────────────────────────────────────
            for (const member of STAFF_FIXTURES) {
                const passwordDigest = await digestTestPassword(member.salt);
                await tx.user.upsert({
                    where: { email: member.email },
                    update: { name: member.name, role: member.role, passwordDigest, disabledAt: null },
                    create: { name: member.name, email: member.email, role: member.role, passwordDigest },
                });
            }

            const facilitator = await tx.user.findUniqueOrThrow({
                where: { email: STAFF_FIXTURES[0].email },
                select: { id: true },
            });

            // ── Sessions + facilitator baseline grant ────────────────
            for (const event of SESSION_FIXTURES) {
                await tx.scheduledSession.upsert({
                    where: { id: event.id },
                    update: {
                        title: event.title,
                        description: event.description,
                        roomName: event.roomName,
                        language: event.language,
                        scheduledAt: event.scheduledAt,
                        isTest: true,
                        status: 'SCHEDULED',
                        paidMode: true,
                        attendeeCap: 150,
                        maxPublishers: 6,
                        facilitatorId: facilitator.id,
                    },
                    create: {
                        id: event.id,
                        title: event.title,
                        description: event.description,
                        roomName: event.roomName,
                        language: event.language,
                        scheduledAt: event.scheduledAt,
                        isTest: true,
                        status: 'SCHEDULED',
                        paidMode: true,
                        attendeeCap: 150,
                        maxPublishers: 6,
                        facilitatorId: facilitator.id,
                    },
                });

                // Look up the baseline grant by its constant placeholder
                // identity, not by staffUserId: if the fixture facilitator's
                // email changes, the re-seed creates a new user and the old
                // baseline row must be reassigned, not duplicated (the
                // (session, identity) unique index would reject the insert).
                await lockGrantSession(tx, event.id);
                await lockGrantStaff(tx, [facilitator.id]);
                const existingFacilitator = await tx.sessionParticipant.findFirst({
                    where: {
                        scheduledSessionId: event.id,
                        participantIdentity: 'test-facilitator-identity',
                    },
                    select: {
                        id: true,
                        publishGrantedAt: true,
                        publishRevokedAt: true,
                    },
                });
                const facilitatorParticipant = existingFacilitator
                    ? await tx.sessionParticipant.update({
                        where: { id: existingFacilitator.id },
                        data: {
                            staffUserId: facilitator.id,
                        },
                        select: {
                            id: true,
                            publishGrantedAt: true,
                            publishRevokedAt: true,
                        },
                    })
                    : await tx.sessionParticipant.create({
                        data: {
                            scheduledSessionId: event.id,
                            staffUserId: facilitator.id,
                            participantIdentity: 'test-facilitator-identity',
                        },
                        select: {
                            id: true,
                            publishGrantedAt: true,
                            publishRevokedAt: true,
                        },
                    });
                await lockGrantParticipants(tx, [facilitatorParticipant.id]);
                if (
                    facilitatorParticipant.publishGrantedAt === null ||
                    facilitatorParticipant.publishRevokedAt !== null
                ) {
                    await transitionParticipantGrant(tx, {
                        scheduledSessionId: event.id,
                        participantId: facilitatorParticipant.id,
                        canPublish: true,
                        now: new Date(),
                        actorUserId: facilitator.id,
                        reason: 'Test fixture facilitator baseline grant',
                    });
                }

                // ── Tickets: 3 issued, 1 bound, 1 revoked, 1 comp ────
                // Codes are near-identical for easy manual typing during
                // testing: TEST-TEST-TEST-TESx (ES) / TENx (EN). They must
                // stay unique across the whole table (codeDigest is @unique)
                // and satisfy TICKET_CODE_PATTERN (16 body chars, A-Z2-9).
                const expiresAt = ticketExpiresAt(event.scheduledAt);
                const letterBase = event.codePrefix === 'TEST-ES' ? 'TES' : 'TEN';
                const tickets = [
                    { letter: 'A', state: 'ISSUED' as const, tier: event.tier },
                    { letter: 'B', state: 'ISSUED' as const, tier: event.tier },
                    { letter: 'C', state: 'ISSUED' as const, tier: event.tier },
                    { letter: 'D', state: 'BOUND' as const, tier: event.tier },
                    { letter: 'E', state: 'REVOKED' as const, tier: event.tier },
                    { letter: 'F', state: 'ISSUED' as const, tier: 'COMP' as const },
                ];

                for (const ticket of tickets) {
                    const code = `TEST-TEST-TEST-${letterBase}${ticket.letter}`;
                    const storage = ticketCodeStorage(code);
                    const boundEmail = ticket.state === 'BOUND' ? ATTENDEE_EMAILS[event.codePrefix] : null;
                    const revoked = ticket.state === 'REVOKED';

                    const existing = await tx.ticketEntitlement.findUnique({
                        where: { codeDigest: storage.codeDigest },
                        select: { id: true },
                    });
                    const data = {
                        scheduledSessionId: event.id,
                        tier: ticket.tier,
                        state: ticket.state,
                        boundEmail,
                        boundAt: boundEmail ? new Date() : null,
                        expiresAt,
                        revokedAt: revoked ? new Date() : null,
                        revocationReason: revoked ? 'Test fixture revoked ticket' : null,
                    };
                    if (existing) {
                        await tx.ticketEntitlement.update({ where: { id: existing.id }, data });
                    } else {
                        await tx.ticketEntitlement.create({
                            data: { ...data, codeDigest: storage.codeDigest, codeLastFour: storage.codeLastFour },
                        });
                    }
                }
            }

            return { staff: STAFF_FIXTURES.length, sessions: SESSION_FIXTURES.length, ticketsPerSession: 6 };
        });

        console.log(
            `Test fixtures ready: ${summary.staff} staff (password "${TEST_STAFF_PASSWORD}"), ` +
            `${summary.sessions} sessions, ${summary.ticketsPerSession} tickets per session.`,
        );
        console.log('Credential list: see db/README.md');
    } finally {
        await prisma.$disconnect();
        await pool.end();
    }
}

main().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : 'Unknown test fixture failure';
    console.error(`Test fixture seed failed: ${message}`);
    process.exitCode = 1;
});
