import type { UiLocale } from '@/lib/i18n';

export const earlyBirdCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · FOUNDING LISTENER',
        title: 'Recuerda tu centro armónico.',
        intro: 'Un campo armónico continuo, compartido alrededor del mundo.',
        live: 'Escucha privada, disponible siempre',
        privateDropIns: 'Una introducción opcional antes de entrar al Beacon',
        membership: 'Acceso Founding Listener',
        signInGoogle: 'Continuar con Google',
        signInApple: 'Continuar con Apple',
        signingIn: 'Abriendo acceso…',
        providerSoon: 'Configuración pendiente',
        signedIn: 'Tu cuenta Listener está lista.',
        enter: 'Entrar al Beacon',
        redeem: 'Activar mi invitación',
        accessNeeded: 'Tu cuenta todavía no tiene una membresía activa.',
        freeTitle: 'Dos horas de Beacon cada día',
        freeDescription: 'Elegí una hora local. Será la misma todos los días y podrás cambiarla después de siete días.',
        listenFreeNow: 'Escuchar gratis ahora',
        chooseFreeTime: 'Elegir otro horario',
        freeStartTime: 'Hora de inicio',
        saveFreeTime: 'Guardar mi horario',
        freeTimeZone: 'Zona horaria',
        nextFreeWindow: 'Tu próxima escucha comienza',
        freeScheduleLocked: 'Podrás cambiar este horario',
        freeScheduleError: 'No pudimos guardar el horario. Inténtalo nuevamente.',
        authError: 'No pudimos completar el acceso. Usa el mismo proveedor con el que creaste tu cuenta o contacta a soporte.',
        privacy: 'Tu cuenta y membresía administran el acceso privado. No creamos historiales personales de escucha.',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · FOUNDING LISTENER',
        title: 'Remember your harmonic center.',
        intro: 'A continuous harmonic field, shared across the world.',
        live: 'Private listening, available whenever you return',
        privateDropIns: 'An optional introduction before entering the Beacon',
        membership: 'Founding Listener access',
        signInGoogle: 'Continue with Google',
        signInApple: 'Continue with Apple',
        signingIn: 'Opening access…',
        providerSoon: 'Configuration pending',
        signedIn: 'Your Listener account is ready.',
        enter: 'Enter the Beacon',
        redeem: 'Activate my invitation',
        accessNeeded: 'Your account does not have an active membership yet.',
        freeTitle: 'Two hours of Beacon every day',
        freeDescription: 'Choose a local start time. It repeats daily and can be changed after seven days.',
        listenFreeNow: 'Listen free now',
        chooseFreeTime: 'Choose another time',
        freeStartTime: 'Start time',
        saveFreeTime: 'Save my listening time',
        freeTimeZone: 'Time zone',
        nextFreeWindow: 'Your next listening window begins',
        freeScheduleLocked: 'You can change this schedule',
        freeScheduleError: 'We could not save the schedule. Please try again.',
        authError: 'We could not complete sign-in. Use the provider that created your account, or contact support.',
        privacy: 'Your account and membership manage private access. We do not create personal listening histories.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdSyntheticEntryCopy = {
    es: {
        title: 'Acceso de equipo · staging',
        description: 'Sólo para pruebas acordadas. Usa una cuenta sintética @e2e.invalid y el código temporal del equipo.',
        name: 'Nombre de prueba',
        email: 'Cuenta sintética',
        accessCode: 'Código de acceso temporal',
        enter: 'Entrar a staging',
        entering: 'Abriendo staging…',
        failed: 'El acceso de prueba no está disponible o los datos no son válidos.',
    },
    en: {
        title: 'Team access · staging',
        description: 'For agreed testing only. Use a synthetic @e2e.invalid account and the team’s temporary access code.',
        name: 'Test name',
        email: 'Synthetic account',
        accessCode: 'Temporary access code',
        enter: 'Enter staging',
        entering: 'Opening staging…',
        failed: 'Test access is unavailable or the supplied details are invalid.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdHomeCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Escuchar',
        mode: 'Cómo querés entrar',
        withIntro: 'Con introducción',
        beaconOnly: 'Solo Beacon',
        skipToBeacon: 'Saltar al Beacon',
        seek: 'Posición',
        prepareDevice: 'Habilitar este dispositivo',
        deviceReady: 'Dispositivo listo. Tocá otra vez para escuchar o elegí un drop-in.',
        deviceLimitClaim: 'Ya hay dos dispositivos activos. Habilitar éste detendrá la escucha en el menos reciente.',
        prepareHelp: 'No pudimos preparar el stream automáticamente. Habilitá este dispositivo antes de escuchar.',
        pause: 'Pausar',
        resume: 'Continuar',
        paused: 'Pausado',
        loading: 'Conectando…',
        reconnecting: 'Restableciendo conexión…',
        unavailable: 'El Beacon no está disponible en este momento.',
        displaced: 'Este dispositivo fue desplazado porque la cuenta ya está escuchando en otros dos dispositivos.',
        spanish: 'Caldeamiento · Español',
        english: 'Warm-up · English',
        dropUnavailable: 'El render aprobado todavía no fue publicado.',
        introSelection: 'Intro antes del Beacon',
        stop: 'Detener',
        playingIntro: 'Sonando intro · después sigue el Beacon',
        playingBeacon: 'Beacon activo',
        stopped: 'Detenido',
        master: 'Volumen',
        signOut: 'Cerrar sesión',
        active: 'Founding Listener activo',
        freeActive: 'Horario Free activo',
        account: 'Cuenta',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Listen',
        mode: 'How you want to enter',
        withIntro: 'With introduction',
        beaconOnly: 'Beacon only',
        skipToBeacon: 'Skip to the Beacon',
        seek: 'Seek',
        prepareDevice: 'Enable this device',
        deviceReady: 'Device ready. Tap again to listen, or choose a drop-in.',
        deviceLimitClaim: 'Two devices are already active. Enabling this one will stop playback on the least recent device.',
        prepareHelp: 'We could not prepare the stream automatically. Enable this device before listening.',
        pause: 'Pause',
        resume: 'Resume',
        paused: 'Paused',
        loading: 'Connecting…',
        reconnecting: 'Restoring connection…',
        unavailable: 'The Beacon is unavailable right now.',
        displaced: 'This device was displaced because the account is already listening on two other devices.',
        spanish: 'Warm-up · Spanish',
        english: 'Warm-up · English',
        dropUnavailable: 'The approved render has not been published yet.',
        introSelection: 'Intro before the Beacon',
        stop: 'Stop',
        playingIntro: 'Playing intro · Beacon follows',
        playingBeacon: 'Beacon playing',
        stopped: 'Stopped',
        master: 'Volume',
        signOut: 'Sign out',
        active: 'Founding Listener active',
        freeActive: 'Free window active',
        account: 'Account',
    },
} satisfies Record<UiLocale, Record<string, string>>;
