import type { UiLocale } from '@/lib/i18n';
import type { ListenerMembershipPresentation } from './membership-presentation';

export const earlyBirdCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        title: 'Recuerda tu centro armónico.',
        intro: 'Un campo armónico continuo, compartido alrededor del mundo.',
        live: 'Escucha dentro del tiempo disponible para tu cuenta',
        privateDropIns: 'Una introducción opcional antes de entrar al Beacon',
        membership: 'Tres horas Free por semana',
        signInGoogle: 'Continuar con Google',
        signInApple: 'Continuar con Apple',
        signingIn: 'Abriendo acceso…',
        magicLinkDivider: 'o',
        magicLinkEmail: 'Correo electrónico',
        magicLinkPlaceholder: 'tu@correo.com',
        magicLinkSend: 'Recibir enlace por correo',
        magicLinkSending: 'Solicitando enlace…',
        magicLinkSent: 'Si el correo puede usarse para este acceso, recibirás un enlace en unos minutos. Caduca a los diez minutos.',
        providerSoon: 'Configuración pendiente',
        signedIn: 'Tu cuenta Listener está lista.',
        signOut: 'Cerrar sesión',
        enter: 'Entrar al Beacon',
        redeem: 'Activar mi invitación',
        accessNeeded: 'Tu cuenta todavía no tiene acceso activo.',
        freeQuotaTitle: 'Tiempo Free semanal',
        freeQuotaNotStarted: 'Tu tiempo empieza cuando escuchas.',
        freeQuotaRemaining: 'Te quedan {time} esta semana',
        freeQuotaAvailable: 'Disponible para escuchar.',
        freeQuotaListening: 'El tiempo se actualiza mientras escuchas.',
        freeQuotaExhausted: 'Usaste tu tiempo Free de esta semana.',
        freeQuotaRenews: 'Volverá a estar disponible al renovarse tu ciclo.',
        freeQuotaResetsIn: 'Se renueva en {time}',
        freeQuotaExtra: 'Incluye {time} de crédito extra.',
        freeQuotaMembershipCta: 'Hazte miembro para tener acceso completo',
        checkoutSandboxTitle: 'Probar membresía Founder',
        checkoutSandboxDetail: 'Checkout de prueba. No usa dinero real.',
        checkoutPayPal: 'Continuar con PayPal',
        checkoutMercadoPago: 'Continuar con Mercado Pago',
        checkoutOpening: 'Abriendo checkout…',
        checkoutUnavailable: 'El checkout de prueba no está disponible ahora.',
        freeQuotaFounder: 'Acceso Founder',
        freeQuotaFreeForAll: 'Acceso libre',
        freeQuotaUnlimited: 'Puedes escuchar sin límite de tiempo.',
        authError: 'No pudimos completar el acceso. Usa el mismo proveedor con el que creaste tu cuenta o contacta a soporte.',
        serviceUnavailableTitle: 'No podemos confirmar tu acceso ahora.',
        identityUnavailable: 'El servicio de identidad no está respondiendo. Tus datos y tu acceso no cambiaron.',
        accessUnavailable: 'No pudimos consultar tu acceso o membresía. No mostraremos un estado estimado.',
        retryAccess: 'Intentar nuevamente',
        privacy: 'Tu cuenta y membresía administran el acceso. Guardamos únicamente tu ciclo y saldo de escucha, no una cronología de reproducciones. La presencia pública es regional, amplia y efímera; nunca revela tu ubicación exacta.',
        membershipInvitation: 'Acceso por invitación',
        membershipPreview: 'Acceso de prueba',
        membershipFounderActive: 'Founding Listener',
        membershipFounderGrace: 'Founder · acceso temporal',
        membershipFounderEnding: 'Founder · activo hasta el final del período',
        membershipFounderPending: 'La membresía Founder todavía no está confirmada.',
        membershipFounderExpired: 'La membresía Founder finalizó.',
        membershipFounderRefunded: 'El pago fue reembolsado y el acceso Founder finalizó.',
        membershipFounderRevoked: 'El acceso Founder fue cerrado.',
        membershipFreeFallback: 'Puedes continuar con la escucha Free disponible para tu cuenta.',
        membershipInvitationEnded: 'La invitación ya no habilita el acceso.',
        membershipPreviewEnded: 'El acceso de prueba finalizó.',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        title: 'Remember your harmonic center.',
        intro: 'A continuous harmonic field, shared across the world.',
        live: 'Listen within the time available to your account',
        privateDropIns: 'An optional introduction before entering the Beacon',
        membership: 'Three Free hours each week',
        signInGoogle: 'Continue with Google',
        signInApple: 'Continue with Apple',
        signingIn: 'Opening access…',
        magicLinkDivider: 'or',
        magicLinkEmail: 'Email address',
        magicLinkPlaceholder: 'you@example.com',
        magicLinkSend: 'Email me a sign-in link',
        magicLinkSending: 'Requesting link…',
        magicLinkSent: 'If this email can be used for access, a link will arrive within a few minutes. It expires after ten minutes.',
        providerSoon: 'Configuration pending',
        signedIn: 'Your Listener account is ready.',
        signOut: 'Sign out',
        enter: 'Enter the Beacon',
        redeem: 'Activate my invitation',
        accessNeeded: 'Your account does not have active access yet.',
        freeQuotaTitle: 'Weekly Free time',
        freeQuotaNotStarted: 'Your time starts when you listen.',
        freeQuotaRemaining: 'You have {time} left this week',
        freeQuotaAvailable: 'Ready when you are.',
        freeQuotaListening: 'Your time updates while you listen.',
        freeQuotaExhausted: 'You have used your Free time for this week.',
        freeQuotaRenews: 'It will be available again when your cycle renews.',
        freeQuotaResetsIn: 'Renews in {time}',
        freeQuotaExtra: 'Includes {time} of extra credit.',
        freeQuotaMembershipCta: 'Become a member for full access',
        checkoutSandboxTitle: 'Try Founder membership',
        checkoutSandboxDetail: 'Test checkout. No real money is used.',
        checkoutPayPal: 'Continue with PayPal',
        checkoutMercadoPago: 'Continue with Mercado Pago',
        checkoutOpening: 'Opening checkout…',
        checkoutUnavailable: 'Test checkout is unavailable right now.',
        freeQuotaFounder: 'Founder access',
        freeQuotaFreeForAll: 'Open access',
        freeQuotaUnlimited: 'You can listen without a time limit.',
        authError: 'We could not complete sign-in. Use the provider that created your account, or contact support.',
        serviceUnavailableTitle: 'We cannot confirm your access right now.',
        identityUnavailable: 'The identity service is not responding. Your data and access have not changed.',
        accessUnavailable: 'We could not check your access or membership. We will not show an estimated state.',
        retryAccess: 'Try again',
        privacy: 'Your account and membership manage access. We keep only your listening cycle and allowance, not a playback timeline. Public presence is broad, regional and ephemeral, and never reveals your exact location.',
        membershipInvitation: 'Invitation access',
        membershipPreview: 'Preview access',
        membershipFounderActive: 'Founding Listener',
        membershipFounderGrace: 'Founder · temporary access',
        membershipFounderEnding: 'Founder · active until the end of the period',
        membershipFounderPending: 'Founder membership is not confirmed yet.',
        membershipFounderExpired: 'Founder membership has ended.',
        membershipFounderRefunded: 'The payment was refunded and Founder access has ended.',
        membershipFounderRevoked: 'Founder access was closed.',
        membershipFreeFallback: 'You can continue with the Free listening available to your account.',
        membershipInvitationEnded: 'The invitation no longer provides access.',
        membershipPreviewEnded: 'Preview access has ended.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdSyntheticEntryCopy = {
    es: {
        title: 'Acceso de equipo · staging',
        description: 'Sólo para pruebas acordadas. Usa una cuenta sintética @e2e.invalid y el código temporal del equipo.',
        name: 'Nombre de prueba',
        email: 'Cuenta sintética',
        accessCode: 'Código de acceso temporal',
        enter: 'Entrar a staging',
        entering: 'Abriendo staging…',
        failed: 'El acceso de prueba no está disponible o los datos no son válidos.',
    },
    en: {
        title: 'Team access · staging',
        description: 'For agreed testing only. Use a synthetic @e2e.invalid account and the team’s temporary access code.',
        name: 'Test name',
        email: 'Synthetic account',
        accessCode: 'Temporary access code',
        enter: 'Enter staging',
        entering: 'Opening staging…',
        failed: 'Test access is unavailable or the supplied details are invalid.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdHomeCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Escuchar',
        playIntroFirst: 'Reproducir introducción primero',
        skipToBeacon: 'Saltar al Beacon',
        seek: 'Posición',
        prepareDevice: 'Habilitar este dispositivo',
        deviceReady: 'Dispositivo listo. Toca otra vez para escuchar o elige una introducción.',
        deviceLimitClaim: 'Ya hay dos dispositivos activos. Habilitar éste detendrá la escucha en el menos reciente.',
        prepareHelp: 'No pudimos preparar el stream automáticamente. Habilita este dispositivo antes de escuchar.',
        pause: 'Pausar',
        resume: 'Continuar',
        paused: 'Pausado',
        loading: 'Conectando…',
        reconnecting: 'Restableciendo conexión…',
        unavailable: 'El Beacon no está disponible en este momento.',
        displaced: 'Este dispositivo fue desplazado porque la cuenta ya está escuchando en otros dos dispositivos.',
        spanish: 'Introducción · Español',
        english: 'Introducción · Inglés',
        dropUnavailable: 'El render aprobado todavía no fue publicado.',
        introSelection: 'Idioma de la introducción',
        stop: 'Detener',
        playingIntro: 'Sonando intro · después sigue el Beacon',
        playingBeacon: 'Beacon activo',
        stopped: 'Detenido',
        master: 'Volumen',
        signOut: 'Cerrar sesión',
        active: 'Listener activo',
        account: 'Cuenta',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Listen',
        playIntroFirst: 'Play introduction first',
        skipToBeacon: 'Skip to the Beacon',
        seek: 'Seek',
        prepareDevice: 'Enable this device',
        deviceReady: 'Device ready. Tap again to listen, or choose a drop-in.',
        deviceLimitClaim: 'Two devices are already active. Enabling this one will stop playback on the least recent device.',
        prepareHelp: 'We could not prepare the stream automatically. Enable this device before listening.',
        pause: 'Pause',
        resume: 'Resume',
        paused: 'Paused',
        loading: 'Connecting…',
        reconnecting: 'Restoring connection…',
        unavailable: 'The Beacon is unavailable right now.',
        displaced: 'This device was displaced because the account is already listening on two other devices.',
        spanish: 'Warm-up · Spanish',
        english: 'Warm-up · English',
        dropUnavailable: 'The approved render has not been published yet.',
        introSelection: 'Introduction language',
        stop: 'Stop',
        playingIntro: 'Playing intro · Beacon follows',
        playingBeacon: 'Beacon playing',
        stopped: 'Stopped',
        master: 'Volume',
        signOut: 'Sign out',
        active: 'Listener active',
        account: 'Account',
    },
} satisfies Record<UiLocale, Record<string, string>>;

type MembershipCopy = { [Key in keyof typeof earlyBirdCopy.en]: string };

export function listenerMembershipPresentationCopy(
    copy: MembershipCopy,
    presentation: ListenerMembershipPresentation,
): { title: string; detail: string | null } | null {
    if (presentation.kind === 'none') return null;

    if (presentation.kind === 'invitation') {
        return {
            title: copy.membershipInvitation,
            detail: presentation.state === 'active' ? null : copy.membershipInvitationEnded,
        };
    }
    if (presentation.kind === 'preview') {
        return {
            title: copy.membershipPreview,
            detail: presentation.state === 'active' ? null : copy.membershipPreviewEnded,
        };
    }

    const provider = presentation.provider === 'paypal' ? 'PayPal' : 'Mercado Pago';
    switch (presentation.state) {
        case 'active': return { title: copy.membershipFounderActive, detail: provider };
        case 'grace': return { title: copy.membershipFounderGrace, detail: provider };
        case 'ending': return { title: copy.membershipFounderEnding, detail: provider };
        case 'pending': return { title: copy.membershipFounderPending, detail: copy.membershipFreeFallback };
        case 'expired': return { title: copy.membershipFounderExpired, detail: copy.membershipFreeFallback };
        case 'refunded': return { title: copy.membershipFounderRefunded, detail: copy.membershipFreeFallback };
        case 'revoked': return { title: copy.membershipFounderRevoked, detail: copy.membershipFreeFallback };
    }
}
