import type { UiLocale } from '@/lib/i18n';
import type { ListenerMembershipPresentation } from './membership-presentation';

export const earlyBirdCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        title: 'Recuerda tu centro armónico.',
        intro: 'Un campo armónico continuo, compartido alrededor del mundo.',
        live: 'Escucha durante el acceso disponible para tu cuenta',
        privateDropIns: 'Una introducción opcional antes de entrar al Beacon',
        membership: 'Primera escucha y horario Free diario',
        signInGoogle: 'Continuar con Google',
        signInApple: 'Continuar con Apple',
        signingIn: 'Abriendo acceso…',
        magicLinkDivider: 'o',
        magicLinkEmail: 'Correo electrónico',
        magicLinkPlaceholder: 'tu@correo.com',
        magicLinkSend: 'Recibir enlace por correo',
        magicLinkSending: 'Solicitando enlace…',
        magicLinkSent: 'Si el correo puede usarse para este acceso, recibirás un enlace en unos minutos. Caduca a los diez minutos.',
        providerSoon: 'Configuración pendiente',
        signedIn: 'Tu cuenta Listener está lista.',
        signOut: 'Cerrar sesión',
        enter: 'Entrar al Beacon',
        redeem: 'Activar mi invitación',
        accessNeeded: 'Tu cuenta todavía no tiene una membresía activa.',
        freeTitle: 'Tu horario diario · 2 horas',
        freeDescription: 'Elige una hora local. Será la misma todos los días y podrás cambiarla después de siete días.',
        listenFreeNow: 'Escuchar gratis ahora',
        chooseFreeTime: 'Elegir otro horario',
        freeStartTime: 'Hora de inicio',
        saveFreeTime: 'Guardar mi horario',
        savingFreeTime: 'Guardando horario…',
        startingFreeTime: 'Abriendo horario Free…',
        cancelFreeTime: 'Volver',
        freeTimeZone: 'Zona horaria',
        savedFreeTime: 'Tu horario diario',
        nextFreeWindow: 'Tu próxima escucha comienza',
        freeScheduleLocked: 'Podrás cambiar este horario',
        freeScheduleError: 'No pudimos guardar el horario. Inténtalo nuevamente.',
        welcomeTitle: 'Tu primera escucha · 30 minutos',
        welcomeListen: 'Escuchar ahora',
        welcomeStarting: 'Abriendo el Beacon…',
        welcomeDescription: 'Tu primera escucha no fija todavía el horario diario.',
        welcomeError: 'No pudimos abrir esta primera escucha. Inténtalo nuevamente.',
        authError: 'No pudimos completar el acceso. Usa el mismo proveedor con el que creaste tu cuenta o contacta a soporte.',
        privacy: 'Tu cuenta y membresía administran el acceso. Durante la escucha sólo compartimos una presencia regional amplia y efímera; nunca tu ubicación exacta ni un historial personal de escucha.',
        membershipInvitation: 'Acceso por invitación',
        membershipPreview: 'Acceso de prueba',
        membershipFounderActive: 'Founder activo',
        membershipFounderGrace: 'Founder · acceso temporal',
        membershipFounderEnding: 'Founder · activo hasta el final del período',
        membershipFounderPending: 'La membresía Founder todavía no está confirmada.',
        membershipFounderExpired: 'La membresía Founder finalizó.',
        membershipFounderRefunded: 'El pago fue reembolsado y el acceso Founder finalizó.',
        membershipFounderRevoked: 'El acceso Founder fue cerrado.',
        membershipFreeFallback: 'Puedes continuar con la escucha Free disponible para tu cuenta.',
        membershipInvitationEnded: 'La invitación ya no habilita el acceso.',
        membershipPreviewEnded: 'El acceso de prueba finalizó.',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        title: 'Remember your harmonic center.',
        intro: 'A continuous harmonic field, shared across the world.',
        live: 'Listen during the access available to your account',
        privateDropIns: 'An optional introduction before entering the Beacon',
        membership: 'A first listen and a daily Free schedule',
        signInGoogle: 'Continue with Google',
        signInApple: 'Continue with Apple',
        signingIn: 'Opening access…',
        magicLinkDivider: 'or',
        magicLinkEmail: 'Email address',
        magicLinkPlaceholder: 'you@example.com',
        magicLinkSend: 'Email me a sign-in link',
        magicLinkSending: 'Requesting link…',
        magicLinkSent: 'If this email can be used for access, a link will arrive within a few minutes. It expires after ten minutes.',
        providerSoon: 'Configuration pending',
        signedIn: 'Your Listener account is ready.',
        signOut: 'Sign out',
        enter: 'Enter the Beacon',
        redeem: 'Activate my invitation',
        accessNeeded: 'Your account does not have an active membership yet.',
        freeTitle: 'Your daily time · 2 hours',
        freeDescription: 'Choose a local start time. It repeats daily and can be changed after seven days.',
        listenFreeNow: 'Listen free now',
        chooseFreeTime: 'Choose another time',
        freeStartTime: 'Start time',
        saveFreeTime: 'Save my listening time',
        savingFreeTime: 'Saving your time…',
        startingFreeTime: 'Opening your Free time…',
        cancelFreeTime: 'Back',
        freeTimeZone: 'Time zone',
        savedFreeTime: 'Your daily time',
        nextFreeWindow: 'Your next listening window begins',
        freeScheduleLocked: 'You can change this schedule',
        freeScheduleError: 'We could not save the schedule. Please try again.',
        welcomeTitle: 'Your first listen · 30 minutes',
        welcomeListen: 'Listen now',
        welcomeStarting: 'Opening the Beacon…',
        welcomeDescription: 'Your first listen does not set your daily time yet.',
        welcomeError: 'We could not open this first listen. Please try again.',
        authError: 'We could not complete sign-in. Use the provider that created your account, or contact support.',
        privacy: 'Your account and membership manage access. While you listen, we share only broad, ephemeral regional presence—never your exact location or a personal listening history.',
        membershipInvitation: 'Invitation access',
        membershipPreview: 'Preview access',
        membershipFounderActive: 'Founder active',
        membershipFounderGrace: 'Founder · temporary access',
        membershipFounderEnding: 'Founder · active until the end of the period',
        membershipFounderPending: 'Founder membership is not confirmed yet.',
        membershipFounderExpired: 'Founder membership has ended.',
        membershipFounderRefunded: 'The payment was refunded and Founder access has ended.',
        membershipFounderRevoked: 'Founder access was closed.',
        membershipFreeFallback: 'You can continue with the Free listening available to your account.',
        membershipInvitationEnded: 'The invitation no longer provides access.',
        membershipPreviewEnded: 'Preview access has ended.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdSyntheticEntryCopy = {
    es: {
        title: 'Acceso de equipo · staging',
        description: 'Sólo para pruebas acordadas. Usa una cuenta sintética @e2e.invalid y el código temporal del equipo.',
        name: 'Nombre de prueba',
        email: 'Cuenta sintética',
        accessCode: 'Código de acceso temporal',
        enter: 'Entrar a staging',
        entering: 'Abriendo staging…',
        failed: 'El acceso de prueba no está disponible o los datos no son válidos.',
    },
    en: {
        title: 'Team access · staging',
        description: 'For agreed testing only. Use a synthetic @e2e.invalid account and the team’s temporary access code.',
        name: 'Test name',
        email: 'Synthetic account',
        accessCode: 'Temporary access code',
        enter: 'Enter staging',
        entering: 'Opening staging…',
        failed: 'Test access is unavailable or the supplied details are invalid.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdHomeCopy = {
    es: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Escuchar',
        mode: 'Cómo quieres entrar',
        withIntro: 'Con introducción',
        beaconOnly: 'Solo Beacon',
        skipToBeacon: 'Saltar al Beacon',
        seek: 'Posición',
        prepareDevice: 'Habilitar este dispositivo',
        deviceReady: 'Dispositivo listo. Toca otra vez para escuchar o elige una introducción.',
        deviceLimitClaim: 'Ya hay dos dispositivos activos. Habilitar éste detendrá la escucha en el menos reciente.',
        prepareHelp: 'No pudimos preparar el stream automáticamente. Habilita este dispositivo antes de escuchar.',
        pause: 'Pausar',
        resume: 'Continuar',
        paused: 'Pausado',
        loading: 'Conectando…',
        reconnecting: 'Restableciendo conexión…',
        unavailable: 'El Beacon no está disponible en este momento.',
        displaced: 'Este dispositivo fue desplazado porque la cuenta ya está escuchando en otros dos dispositivos.',
        spanish: 'Introducción · Español',
        english: 'Introducción · Inglés',
        dropUnavailable: 'El render aprobado todavía no fue publicado.',
        introSelection: 'Intro antes del Beacon',
        stop: 'Detener',
        playingIntro: 'Sonando intro · después sigue el Beacon',
        playingBeacon: 'Beacon activo',
        stopped: 'Detenido',
        master: 'Volumen',
        signOut: 'Cerrar sesión',
        active: 'Listener activo',
        freeActive: 'Horario Free activo',
        welcomeActive: 'Primera escucha activa',
        account: 'Cuenta',
    },
    en: {
        eyebrow: 'HARMONIC BEACON · LISTENER',
        heading: 'Beacon',
        listen: 'Listen',
        mode: 'How you want to enter',
        withIntro: 'With introduction',
        beaconOnly: 'Beacon only',
        skipToBeacon: 'Skip to the Beacon',
        seek: 'Seek',
        prepareDevice: 'Enable this device',
        deviceReady: 'Device ready. Tap again to listen, or choose a drop-in.',
        deviceLimitClaim: 'Two devices are already active. Enabling this one will stop playback on the least recent device.',
        prepareHelp: 'We could not prepare the stream automatically. Enable this device before listening.',
        pause: 'Pause',
        resume: 'Resume',
        paused: 'Paused',
        loading: 'Connecting…',
        reconnecting: 'Restoring connection…',
        unavailable: 'The Beacon is unavailable right now.',
        displaced: 'This device was displaced because the account is already listening on two other devices.',
        spanish: 'Warm-up · Spanish',
        english: 'Warm-up · English',
        dropUnavailable: 'The approved render has not been published yet.',
        introSelection: 'Intro before the Beacon',
        stop: 'Stop',
        playingIntro: 'Playing intro · Beacon follows',
        playingBeacon: 'Beacon playing',
        stopped: 'Stopped',
        master: 'Volume',
        signOut: 'Sign out',
        active: 'Listener active',
        freeActive: 'Free window active',
        welcomeActive: 'First listen active',
        account: 'Account',
    },
} satisfies Record<UiLocale, Record<string, string>>;

type MembershipCopy = { [Key in keyof typeof earlyBirdCopy.en]: string };

export function listenerMembershipPresentationCopy(
    copy: MembershipCopy,
    presentation: ListenerMembershipPresentation,
): { title: string; detail: string | null } | null {
    if (presentation.kind === 'none') return null;

    if (presentation.kind === 'invitation') {
        return {
            title: copy.membershipInvitation,
            detail: presentation.state === 'active' ? null : copy.membershipInvitationEnded,
        };
    }
    if (presentation.kind === 'preview') {
        return {
            title: copy.membershipPreview,
            detail: presentation.state === 'active' ? null : copy.membershipPreviewEnded,
        };
    }

    const provider = presentation.provider === 'paypal' ? 'PayPal' : 'Mercado Pago';
    switch (presentation.state) {
        case 'active': return { title: copy.membershipFounderActive, detail: provider };
        case 'grace': return { title: copy.membershipFounderGrace, detail: provider };
        case 'ending': return { title: copy.membershipFounderEnding, detail: provider };
        case 'pending': return { title: copy.membershipFounderPending, detail: copy.membershipFreeFallback };
        case 'expired': return { title: copy.membershipFounderExpired, detail: copy.membershipFreeFallback };
        case 'refunded': return { title: copy.membershipFounderRefunded, detail: copy.membershipFreeFallback };
        case 'revoked': return { title: copy.membershipFounderRevoked, detail: copy.membershipFreeFallback };
    }
}
