#!/bin/sh
set -eu

: "${DATABASE_URL:?production database URL is required}"

# Prisma's `schema` query parameter is not a libpq URI parameter. The
# production admin URL is generated by this deployment package with exactly
# this suffix; reject any other shape instead of silently rewriting arbitrary
# connection options.
case "$DATABASE_URL" in
  *'?schema=public') pg_dump_url=${DATABASE_URL%"?schema=public"} ;;
  *)
    echo 'beacon-account: production database URL must end with the reviewed public schema parameter' >&2
    exit 2
    ;;
esac

unset DATABASE_URL
exec pg_dump --format=custom --no-owner --no-acl "$pg_dump_url"
